apiVersion: v1
kind: Service
metadata:
  name: todo-service
spec:
  selector:
    app.kubernetes.io/name: todo
  ports:
    - name: name-of-service-port-todo
      protocol: TCP
      port: 80
      targetPort: http-web-svc
