name: build_deploy_aks
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: ACR build
        id: build-push-acr
        uses: azure/acr-build@v1
        with:
          service_principal: ${{ secrets.AZURE_CLIENT_ID }}
          service_principal_password: ${{ secrets.AZURE_CLIENT_SECRET }}
          tenant: ${{ secrets.AZURE_TENANT_ID }}
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          repository: todo
          image: api
          folder: src/ToDo
          branch: main
          tag: ${{ github.sha }}
      - name: ACR worker build
        id: build-push-acr-worker
        uses: azure/acr-build@v1
        with:
          service_principal: ${{ secrets.AZURE_CLIENT_ID }}
          service_principal_password: ${{ secrets.AZURE_CLIENT_SECRET }}
          tenant: ${{ secrets.AZURE_TENANT_ID }}
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          repository: todo
          image: worker
          folder: src/worker/ToDoEventsProcessor
          branch: main
          tag: ${{ github.sha }}
      - name: Azure login
        id: login
        uses: azure/login@v1.4.3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Set AKS context
        id: set-context
        uses: azure/aks-set-context@v3
        with:
          resource-group: team1
          cluster-name: vsoftlabteam1 #nazwa klastra AKS
      - name: Setup kubectl
        id: install-kubectl
        uses: azure/setup-kubectl@v3
      - name: Deploy to AKS
        id: deploy-aks
        uses: Azure/k8s-deploy@v4
        with:
          namespace: "default"
          manifests: |
            src/ToDo/deployment.yaml
            src/ToDo/service.yaml
          images: "${{ secrets.ACR_LOGIN_SERVER }}.azurecr.io/todo/api:${{ github.sha }}"
          pull-images: false
